POST http://localhost:3000/client/postTrainingData?clientId=1234&clientSecret=123 HTTP/1.1
content-type: application/json

{
    "documentsAndAnswers": {
        "documents": [
            {
                "languageCode": "en",
                "inputText": "Hi",
                "intentName": "greetings.hi"
            }
        ],
        "answers": [
            {
                "languageCode": "en",
                "intentName": "greetings.hi",
                "answerText": ":) Hi"
            }
        ]
    },
    "defaultResponses": [
        "I don't know what to say.",
        "What should I say?"
    ]
}